### ISSUE TITLE
should all normalized numbers be valid?

### ISSUE THREAD

**Issue by mooreniemi** [joost/phony_rails#162]
I use the faker gem to generate phone numbers in my app. Many generated numbers, even after being normalized by phony_rails, throw validation errors. From going through the data generated, it seems to be numbers beginning with "(xxx)" (where x is some digit). 

1. Can you help me understand why these numbers are invalid? I'm happy to take this to the faker gem if they're generating invalid numbers.
2. Is the expected return value of `phony_normalized` always a valid number? If it isn't, should this method throw or return nil instead rather than waiting for downstream errors on save?
3. Can the public API provide a `valid?` method on normalized numbers ie `PhonyRails.validate_number(number_string)` so I can get earlier feedback?

```ruby
faker_number = Faker::PhoneNumber.cell_phone
# =>  "(113) 975-5979"
normalized_number = faker_number.phony_normalized
# => "139755979"
u.mobile_phone = normalized_number
u.save!
# => ActiveRecord::RecordInvalid: Validation failed: Mobile phone is an invalid number
```

I also tried using strict to drop values to nil if they're "bad" before normalization with a fallback number:

```ruby
Faker::PhoneNumber.cell_phone.
        phony_formatted(strict: true).try(:phony_normalized) || FALLBACK_NUMBER
# => "00 038 2524"
```

But "00 038 2524" was considered an invalid number by the validator. I feel like the PhonyRails API should not be returning a value it can't consume. Can I help fix this or do you disagree that this is a concern?

**Comment by joost** [comment]
It might have to do with he phony gem checking for actual existing prefixes.

**Comment by CollinGraves** [comment]
@joost what should we do about this? I can try and submit a patch this week.

**Comment by joost** [comment]
A patch is always welcome :)

**Comment by CollinGraves** [comment]
Alright @mooreniemi I was able to dig in to your bug a bit. 

The Phony implementation goes as granular as knowing which area codes belong to which country codes. Meaning that in your example, an area code of `(113)` belongs to the `country_code` of 'GB'. Because you're not passing a `country_code` in your options hash, Phony will fall back to your `default_country_code` declaration, which, unless it's in fact 'GB', will render your number format incorrect. In your case, it looks like your `default_country_code` setting is set to 'US', which is why that front '1' is getting stripped off the number (area codes beginning in '1' are invalid in the United States, btw).

I proved this by merging `country_code: 'GB'` in to the options hash and testing the output of `#normalize_number`.

Of course, this really only addresses your first point. We can decide what's best for the remaining issues, but I'm assuming the easiest fix is to fix your Faker setup.

In your Faker initialization, add the following: 
```
Faker::Config.locale = 'en-US'
```

This will prevent the gem from producing numbers that are invalid for the US.
