### ISSUE TITLE
Nil return values for normalize cause validations to pass

### ISSUE THREAD

**Issue by vdolbilov** [joost/phony_rails#92]
Hi, I have in my User model:

    phony_normalize :phone_number, default_country_code: 'US'
    validates :phone_number, phony_plausible: true

One thing I noticed is that setting a string value that causes `#normalize_number` to return `nil` will pass validations:

    u = User.find(blah)
    u.phone_number = "Clearly invalid"
    u.save!
    => true
    u.phone_number
    => nil

However,

    PhonyRails.plausible_number? nil
    => false

Am I doing the validation incorrectly? Setting a phone number like "12345" causes the validation to fail as expected.

**Comment by joost** [comment]
Have you tried `allow_nil: false` ?

**Comment by joost** [comment]
@pjg did most of the validator stuff so he might know the answer :)

**Comment by dmdeller** [comment]
The problem seems to be that PhonyRails attempts to normalize the number *before* validating, which transforms the value into `nil` if it was invalid, causing it to pass validation when blank is allowed and an invalid value is submitted.

I've had success by avoiding using both `phony_normalize` and `validates_plausible_phone` entirely, and using this approach instead:

    PHONE_DEFAULT_COUNTRY_CODE = 'US'

    validate :phone_looks_real
  
    after_validation :normalize_phone
    
    def phone_looks_real
      if !PhonyRails.plausible_number?(self.phone, default_country_code: PHONE_DEFAULT_COUNTRY_CODE)
        errors.add(:phone, "doesn't look like a valid phone number")
      end
    end
    
    def normalize_phone
      self.phone = PhonyRails.normalize_number(self.phone, default_country_code: PHONE_DEFAULT_COUNTRY_CODE)
    end

This seems to work with any US phone number I throw at it, with or without any of the following: dashes, spaces, parentheses, country code. It rejects strings like 'foo' as invalid. It also allows leaving the field blank, which is what I needed.

**Comment by vdolbilov** [comment]
Thanks! I ended up doing basically the same thing since I needed to allow nil values. Closing this issue since this is a good solution.

**Comment by pjg** [comment]
I like when things get resolved before I have time to look into them ;) It's been ages since I've looked at phony's source code.

**Comment by bartoszkopinski** [comment]
I'm afraid it's not really resolved as the behaviour is still inconsistent if I don't specify `presence: true`:
```ruby
phony_normalize :phone_number, default_country_code: 'GB'
validates :phone_number, phony_plausible: true
```
```ruby
pry(main)> u.phone_number
=> "+447400018923"
pry(main)> u.phone_number = '123'
=> "123"
pry(main)> u.phone_number
=> "123"
pry(main)> u.valid?
=> false
pry(main)> u.phone_number = 'asd'
=> "asd"
pry(main)> u.valid?
=> true
pry(main)> u.phone_number
=> nil
```

@joost @pjg any chances of fixing it?

**Comment by pjg** [comment]
I don't use the gem any more, so I don't think I'll be able to help. Sorry!
