### ISSUE TITLE
Using a number different from the country

### ISSUE THREAD

**Issue by phillipp** [joost/phony_rails#97]
Hi,
thanks for this great gem! I'm not sure if this is is a phony or phony_rails issue:

I have a validation in the model that goes like this:

```
phony_normalize :phone
  validates :phone, phony_plausible: true, presence: true
```

This works fine when the user wants to add a number that has the same country code/prefix than the country_code from the address. If the user types a number from another country, prefixed by + so that it's clear that there already is a country code the country prefix from the record's country code is added.

Is that a bug or a feature? In this case I want that the user can specify a number from another country, but the number is prefixed by default with the country prefix from the record's country_code. Is that possible? I saw that there is an undocumented `ignore_record_country_code` option but that seems to ignore the country code at all.

**Comment by joost** [comment]
Lets ask @cinconnu .. creator of the validation stuff.

**Comment by ddidier** [comment]
I don't remember well since it has been quite some time... but I think you actually can tell that's a bug, or at least the feature was overlooked :)
I don't have any time to fix this but I took a look at the code and the `+` sign should be taken into account in the `validate_each` method of [PhonyPlausibleValidator](https://github.com/joost/phony_rails/blob/01ba8a21ff874a544ca28bcf9a198abb32a4cc1d/lib/validators/phony_validator.rb). There should be 2 cases, validate without the country code if the `+` sign is present at the start of the number, use the current code otherwise.

**Comment by phillipp** [comment]
So I assume a pull request is welcome?
